// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzP7lPQs3SLUj1gcZxBx65fUe_sVHS_2M',
    appId: '1:944630789596:web:0a06d7413c9664336acb19',
    messagingSenderId: '944630789596',
    projectId: 'fusandafe-ac9ee',
    authDomain: 'fusandafe-ac9ee.firebaseapp.com',
    storageBucket: 'fusandafe-ac9ee.firebasestorage.app',
    measurementId: 'G-00Q2GD2MPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Avx0q5aKcO3zxP_II4EXR1Ulf4TV8f0',
    appId: '1:944630789596:android:feb4cce6bf33da0f6acb19',
    messagingSenderId: '944630789596',
    projectId: 'fusandafe-ac9ee',
    storageBucket: 'fusandafe-ac9ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC598I1cKe70p0UtwPgx80WmWGr7rFfbjI',
    appId: '1:944630789596:ios:a5bd4fddb464edef6acb19',
    messagingSenderId: '944630789596',
    projectId: 'fusandafe-ac9ee',
    storageBucket: 'fusandafe-ac9ee.firebasestorage.app',
    iosBundleId: 'com.example.fusandafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC598I1cKe70p0UtwPgx80WmWGr7rFfbjI',
    appId: '1:944630789596:ios:a5bd4fddb464edef6acb19',
    messagingSenderId: '944630789596',
    projectId: 'fusandafe-ac9ee',
    storageBucket: 'fusandafe-ac9ee.firebasestorage.app',
    iosBundleId: 'com.example.fusandafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzP7lPQs3SLUj1gcZxBx65fUe_sVHS_2M',
    appId: '1:944630789596:web:8f4e91ea3cfbfb796acb19',
    messagingSenderId: '944630789596',
    projectId: 'fusandafe-ac9ee',
    authDomain: 'fusandafe-ac9ee.firebaseapp.com',
    storageBucket: 'fusandafe-ac9ee.firebasestorage.app',
    measurementId: 'G-8TVNVQ4S6N',
  );
}
